### ISSUE TITLE
Typo in AssemblyInfo.cs

### ISSUE THREAD

**Issue by azavarben** [Sitefinity/mailchimp-connector-sample#1]
Extra bracket here: https://github.com/Sitefinity/mailchimp-connector-sample/blob/4a440ed7ee6fac84dd0402e86fb461478d9af750/Telerik.Sitefinity.MailchimpConnector/Properties/AssemblyInfo.cs#L15

**Comment by yasen-yankov** [comment]
Fixed. Thank you.
