### ISSUE TITLE
Any possibility to upgrade it to the latest SF versions ? 

### ISSUE THREAD

**Issue by Dav1DL** [Sitefinity/mailchimp-connector-sample#25]
Hi All, 
we are trying to use this useful connector for our projects that are running on Sitefinity 14.0 but we are experiencing several compatibility issues with related dll . 
Is there any chance that this connector will be upgraded to work properly also with the latest version of the CMS ? 
Thanks in advance
David

**Comment by bkirpiev** [comment]
Hi, Dav1DL 
I'll look into this issue and will write you as soon as posible.
